name: üöÄ Build & Push Docker image

on:
  push:
    tags:
      - "v*" # Ex: v0.0.1, v1.0.0-beta
    branches:
      - main # Build automatique sur merge dans main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: üßæ Checkout repository
        uses: actions/checkout@v4

      - name: üß∞ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: üîê Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: üè∑Ô∏è Extract version tag (if exists)
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
          fi

      - name: üê≥ Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            spino13/futurisys:${{ env.TAG }}
            ${{ startsWith(env.TAG, 'v') && !contains(env.TAG, '-') && 'spino13/futurisys:latest' || '' }}
          build-args: |
            ENVIRONMENT=production
            DEBUG=False
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            API_VERSION=${{ env.TAG }}
      - name: üöÄ Push to Hugging Face Space
        if: github.ref == 'refs/heads/main'
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          echo "üîë Configuring Git for Hugging Face..."
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          echo "üîó Adding Hugging Face Space remote..."
          git remote add space https://user:${HF_TOKEN}@huggingface.co/spaces/spino13/futurisys || true

          echo "üì§ Pushing latest commit to HF Space..."
          git push --force space main
